In [1]:
import pandas as pd

In [7]:
# Data Preprocessing
file=pd.read_csv("C:\\Users\\91755\\Desktop\\Excelr Assignments\\Recommendation System\\Recommendation System\\anime.csv")
file

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12289    4.15      211  
12290    4.28      183  
12291    4.88      219  
12292    4.98      175  
12293    5.46      142  

[12294 rows x 7 columns]

In [9]:
file.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [13]:
file['rating']=file['rating'].fillna(file['rating'].mean())
file['rating']

0        9.37
1        9.26
2        9.25
3        9.17
4        9.16
         ... 
12289    4.15
12290    4.28
12291    4.88
12292    4.98
12293    5.46
Name: rating, Length: 12294, dtype: float64

In [15]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12294 non-null  int64  
 1   name      12294 non-null  object 
 2   genre     12232 non-null  object 
 3   type      12269 non-null  object 
 4   episodes  12294 non-null  object 
 5   rating    12294 non-null  float64
 6   members   12294 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB


In [17]:
file.describe()

anime_id        rating       members
count  12294.000000  12294.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.017096  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.900000  2.250000e+02
50%    10260.500000      6.550000  1.550000e+03
75%    24794.500000      7.170000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [19]:
file.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [35]:
import warnings
from sklearn.feature_extraction.text import CountVectorizer

# Suppress warnings
warnings.filterwarnings("ignore", category=UserWarning, module="sklearn.feature_extraction.text")

# Convert genres into numerical representation
vectorizer = CountVectorizer(tokenizer=lambda x: x.split(", "))
genre_matrix = vectorizer.fit_transform(file['genre'].fillna(""))
# Check feature names
print(vectorizer.get_feature_names_out())

# Check the resulting matrix
print(genre_matrix.toarray())



['' 'action' 'adventure' 'cars' 'comedy' 'dementia' 'demons' 'drama'
 'ecchi' 'fantasy' 'game' 'harem' 'hentai' 'historical' 'horror' 'josei'
 'kids' 'magic' 'martial arts' 'mecha' 'military' 'music' 'mystery'
 'parody' 'police' 'psychological' 'romance' 'samurai' 'school' 'sci-fi'
 'seinen' 'shoujo' 'shoujo ai' 'shounen' 'shounen ai' 'slice of life'
 'space' 'sports' 'super power' 'supernatural' 'thriller' 'vampire' 'yaoi'
 'yuri']
[[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [47]:
#Normalize numerical features
from sklearn.preprocessing import MinMaxScaler

# Replace 'Unknown' with NaN, then fill NaN values with 0
file['episodes'] = file['episodes'].replace('Unknown', 0).fillna(0)
file['rating'] = file['rating'].replace('Unknown', 0).fillna(0)

# Convert columns to numeric
file['episodes'] = pd.to_numeric(file['episodes'], errors='coerce').fillna(0)
file['rating'] = pd.to_numeric(file['rating'], errors='coerce').fillna(0)

# Scale the columns
scaler = MinMaxScaler()
file[['episodes', 'rating']] = scaler.fit_transform(file[['episodes', 'rating']])

# Display the first few rows of the updated file
print(file.head())



   anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type  episodes  \
0               Drama, Romance, School, Supernatural  Movie  0.000550   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV  0.035204   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV  0.028053   
3                                   Sci-Fi, Thriller     TV  0.013201   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV  0.028053   

     rating  members  
0  0.924370   200630  
1  0.911164   793665  
2  0.909964   114262  
3  0.900360   673572  
4  0.899160   151266  


In [49]:
import numpy as np
combined_features=np.hstack([genre_matrix.toarray(),file[['episodes','rating']].values])
combined_features

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 5.50055006e-04, 9.24369748e-01],
       [0.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 3.52035204e-02, 9.11164466e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.80528053e-02, 9.09963986e-01],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.20022002e-03, 3.85354142e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 5.50055006e-04, 3.97358944e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 5.50055006e-04, 4.54981993e-01]])

In [59]:
#Recommendation System
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix

# Convert combined_features to a sparse matrix if it's not already sparse
sparse_features = csr_matrix(combined_features)

# Compute cosine similarity using sparse matrices
similarity_matrix = cosine_similarity(sparse_features, dense_output=False)

MemoryError: Unable to allocate 577. MiB for an array with shape (151141890,) and data type int32